### PR TITLE
Add Block Styles to Card Tab

### PR DESCRIPTION
**Pull request by fabiankaegy**
With this PR I am adding the Block Styles Variations to the Card tab of the Block.

Screen Shot 2020-08-01 at 19 41 04

### CODE REVIEW

**Comment by youknowriad** [comment]
Thanks for the PR @fabiankaegy 

As you can see on #25 I was actually thinking of automatically adding stories for the different style variations. What do you think about that?

**Comment by fabiankaegy** [comment]
Yeah and I think that would be super cool :) I created a branch locally to play around with it. But I still think there is value in seeing the class names for every stylevariation in one place :)

**Comment by youknowriad** [comment]
I can see that yes 👍 

Unrelated but I wonder why we chose to use `-` as a separator for support flags instead of `:` like style variations and attributes.

**Comment by fabiankaegy** [comment]
You are Right. When I added the supports section I thought of the actual value to be different from the type for example in the attributes. But I agree that unification is better here.

**Pull request merged**
